on:
    push:
        branches: master

jobs: 
    bind:
        name: Bind
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: ls 
            - run: docker build -t test_binder ./github && docker run -e "GITHUB_TOKEN=${{secrets.BINDER_TOKEN}}"  --name binder-test-container test_binder
            